main: com.snorklingturtle.cameraplugin.CameraPlugin
name: CameraPlugin
version: 1.0.0
description: A Minecraft camera plugin that renders photos onto maps.
author: SkooterKurt
api-version: 1.21
softdepend: [Multiverse-Core]

commands:
  camera:
    description: Camera plugin commands.
    usage: /camera <help|aa|shade|shadow|dither|frame>
    permission: camera.use

permissions:
  camera.use:
    description: Allows using the camera item and command.
    default: op

