main: com.snorklingturtle.cameraplugin.CameraPlugin
name: CameraPlugin
version: 1.0.0
description: A Minecraft camera plugin that renders photos onto maps.
author: SkooterKurt
api-version: 1.21
softdepend: [Multiverse-Core]

commands:
  camera:
    description: Camera plugin commands.
    usage: /camera <help|aa|shade|shadow|dither|frame>
    permission: camera.command

permissions:
  camera.craft:
    description: Allows crafting the camera.
    default: true
  camera.use:
    description: Allows using the camera item.
    default: true
  camera.command:
    description: Allows camera commands /camera
    default: op
  camera.usepaper:
    description: Require paper when taking photos
    default: true